// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPmZf0VR9z6QVkSaQqLDHNZxCk7nqu3m8',
    appId: '1:871082262941:web:fc25d79e26e5c423ee6f74',
    messagingSenderId: '871082262941',
    projectId: 'hoaxhunter-ar',
    authDomain: 'hoaxhunter-ar.firebaseapp.com',
    storageBucket: 'hoaxhunter-ar.firebasestorage.app',
    measurementId: 'G-3R6WKCS0S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtK9Bb6MgDtsbfBDt7uYQKCETkhthjKvs',
    appId: '1:871082262941:android:8bbc55be59c0fa74ee6f74',
    messagingSenderId: '871082262941',
    projectId: 'hoaxhunter-ar',
    storageBucket: 'hoaxhunter-ar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx4u6y8dQkhkjryCRUaMzhvY8DCKTFxF0',
    appId: '1:871082262941:ios:9c927da5dc7d2bffee6f74',
    messagingSenderId: '871082262941',
    projectId: 'hoaxhunter-ar',
    storageBucket: 'hoaxhunter-ar.firebasestorage.app',
    iosBundleId: 'com.example.arQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx4u6y8dQkhkjryCRUaMzhvY8DCKTFxF0',
    appId: '1:871082262941:ios:9c927da5dc7d2bffee6f74',
    messagingSenderId: '871082262941',
    projectId: 'hoaxhunter-ar',
    storageBucket: 'hoaxhunter-ar.firebasestorage.app',
    iosBundleId: 'com.example.arQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPmZf0VR9z6QVkSaQqLDHNZxCk7nqu3m8',
    appId: '1:871082262941:web:644a6ce5a0fa4c42ee6f74',
    messagingSenderId: '871082262941',
    projectId: 'hoaxhunter-ar',
    authDomain: 'hoaxhunter-ar.firebaseapp.com',
    storageBucket: 'hoaxhunter-ar.firebasestorage.app',
    measurementId: 'G-F816X7B5H9',
  );
}
